#sudo: required
#language: java
#before_install:
#  - chmod +x mvnw
#  - mvn clean install
#
language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
#install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script:
#  - mvn test

#dist: trusty
#before_install:
#  - chmod +x mvnw
#sudo: false


# git strips the wrapper jar file so we have to force its download during the build
#install:
#  - mvn -N io.takari:maven:wrapper
#  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V